{% set name = "uuid-utils" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uuid_utils-{{ version }}.tar.gz
  sha256: 252bd3d311b5d6b7f5dfce7a5857e27bb4458f222586bb439463231e5a9cbd64

build:
  number: 0
  skip: true  # [py<39]
  script:
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - uuid_utils
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v # [not osx]
    # test_getnode is marked as xfail on linux but it seems doesn't work on macOS too.
    - pytest -v -k "not test_getnode"  # [osx]


about:
  home: https://github.com/aminalaee/uuid-utils
  summary: Drop-in replacement for Python UUID in Rust
  description: |
    Python UUID implementation using Rust's UUID library. 
    This will make uuid4 function around 10x faster.
  dev_url: https://github.com/aminalaee/uuid-utils
  doc_url: https://aminalaee.dev/uuid-utils/
  license: BSD-3-Clause
  license_file: 
    - LICENSE.md
    - THIRDPARTY.yml
  license_family: BSD

extra:
  recipe-maintainers:
    - moritzwilksch
