{% set name = "uuid-utils" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uuid_utils-{{ version }}.tar.gz
  sha256: 7e828735e8b84186e37ba0942f8873c29fb3d175eaeb5bb0b5ce7e10464e7858

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - matruin                                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
  run:
    - python

test:
  imports:
    - uuid_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aminalaee/uuid-utils
  summary: Drop-in replacement for Python UUID in Rust
  dev_url: https://github.com/aminalaee/uuid-utils
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
