{% set name = "uuid-utils" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uuid_utils-{{ version }}.tar.gz
  sha256: 5db0e1890e8f008657ffe6ded4d9459af724ab114cfe82af1557c87545301539

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
  run:
    - python

test:
  imports:
    - uuid_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aminalaee/uuid-utils
  summary: Drop-in replacement for Python UUID in Rust
  dev_url: https://github.com/aminalaee/uuid-utils
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
