{% set name = "uuid-utils" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uuid_utils-{{ version }}.tar.gz
  sha256: 5db0e1890e8f008657ffe6ded4d9459af724ab114cfe82af1557c87545301539

build:
  number: 0
  skip: true  # [py<39]
  missing_dso_whitelist:
  - $RPATH/ld64.so.1  # [s390x]
  script:
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - uuid_utils
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/aminalaee/uuid-utils
  summary: Drop-in replacement for Python UUID in Rust
  description: |
    Python UUID implementation using Rust's UUID library. 
    This will make uuid4 function around 10x faster.
  dev_url: https://github.com/aminalaee/uuid-utils
  doc_url: https://aminalaee.dev/uuid-utils/
  license: BSD-3-Clause
  license_file: 
    - LICENSE.md
    - THIRDPARTY.yml
  license_family: BSD

extra:
  recipe-maintainers:
    - moritzwilksch
